# ============================================================
# LinBox shell integration (auto-generated by LinBox installer)
# 在真实 Termux shell 中提供 LinBox 联动命令：
#   theme win95|xp|win7|win10|win11   切换窗口主题
#   start <app>                      打开 LinBox 应用（terminal/x11/settings…）
#   apps                             列出可打开的应用
#   open <url>                       用系统浏览器打开网址
#   winver                           显示 LinBox 版本信息
# 原理：命令写入 FIFO，由 App 主进程读取并执行。
# ============================================================

# ---- dpkg 包装器自愈（fix7 兜底，静默）----
# dpkg 包自升级会用新真身 ELF 覆盖 bin/dpkg（包装器副本）。apt 经
# apt.conf.d/99linbox 走 libexec/linbox/dpkg 不受影响，但用户直接
# 调用的 bin/dpkg 需要恢复：若其为 ELF（被覆盖），先提升为
# dpkg.real（保持版本最新），再从包装器本体恢复副本。
_linbox_heal_dpkg() {
    _bin="$PREFIX/bin/dpkg"
    _wrap="$PREFIX/libexec/linbox/dpkg"
    _real="$PREFIX/libexec/linbox/dpkg.real"
    [ -f "$_wrap" ] || return 0
    if [ -f "$_bin" ]; then
        _magic=$(head -c 4 "$_bin" 2>/dev/null | od -An -tx1 2>/dev/null | tr -d ' \n')
        if [ "$_magic" = "7f454c46" ]; then
            if [ ! -f "$_real" ] || [ "$_bin" -nt "$_real" ]; then
                cp -f "$_bin" "$_real.tmp" 2>/dev/null \
                    && chmod 700 "$_real.tmp" 2>/dev/null \
                    && mv -f "$_real.tmp" "$_real" 2>/dev/null
            fi
        fi
    fi
    if ! cmp -s "$_wrap" "$_bin" 2>/dev/null; then
        cp -f "$_wrap" "$_bin.tmp" 2>/dev/null \
            && chmod 700 "$_bin.tmp" 2>/dev/null \
            && mv -f "$_bin.tmp" "$_bin" 2>/dev/null
    fi
    return 0
}
_linbox_heal_dpkg
unset -f _linbox_heal_dpkg

# ---- dpkg 兜底配置 + Pre-Install-Pkgs 钩子（fix8.5，无条件重写）----
# 官方 deb 中漏经 linbox-debfix 重写的 /data/data/com.termux 成员
# （如裸目录条目 ./data/data/com.termux）会让 dpkg 报
# "unable to stat ... Permission denied"。path-exclude 让 dpkg 直接
# 跳过这些成员；force-confold 消除配置文件升级交互提示；
# Pre-Install-Pkgs 钩子把全部 deb 在 dpkg 前交给 linbox-debfix 重写
# （绕过包装器的独立第二路径）。
# 三路写入互为兜底：安装器(Kotlin)/本函数(会话启动)/linbox-dpkg(每次调用)。
_linbox_ensure_dpkg_fix() {
    _cfg="$PREFIX/etc/dpkg/dpkg.cfg.d/99-linbox-fix"
    _acfg="$PREFIX/etc/apt/apt.conf.d/99-linbox-fix"
    mkdir -p "${_cfg%/*}" "${_acfg%/*}" 2>/dev/null
    printf '%s\n' \
        '# LinBox (com.linbox) dpkg 兜底修复（fix8.5）' \
        '# 跳过官方 deb 中漏经重写的 /data/data/com.termux 成员' \
        '# （如裸目录条目），否则 dpkg 落盘时报 Permission denied。' \
        'path-exclude=/data/data/com.termux' \
        'path-exclude=/data/data/com.termux/*' \
        'force-confold' \
        > "$_cfg" 2>/dev/null
    printf '%s\n' \
        '// LinBox (com.linbox) dpkg 兜底修复（fix8.5）' \
        '// path-exclude/force-confold 双保险；Pre-Install-Pkgs 把全部' \
        '// deb 在 dpkg 前交给 linbox-debfix 重写（独立第二路径）。' \
        'DPkg::Options:: "--path-exclude=/data/data/com.termux";' \
        'DPkg::Options:: "--path-exclude=/data/data/com.termux/*";' \
        'DPkg::Options:: "--force-confold";' \
        'DPkg::Pre-Install-Pkgs:: "/data/data/com.linbox/files/usr/bin/linbox-debfix";' \
        > "$_acfg" 2>/dev/null
    # dpkg 数据库全量重写（fix8.5，一次性）：清除历史残留的
    # com.termux 路径（info/*.list、status），根除 unpack-over
    # 旧清单时对旧路径的 stat 失败。
    _dbstamp="$PREFIX/var/lib/linbox/dbfull.stamp"
    if [ -x "$PREFIX/bin/linbox-reprefix" ] && [ ! -f "$_dbstamp" ]; then
        "$PREFIX/bin/linbox-reprefix" --full --quiet >/dev/null 2>&1
        : > "$_dbstamp" 2>/dev/null
    fi
    # 部署指纹（fix8.5）：每次会话打印一行。看到本行=新版 APK 已部署、
    # 修复链路（deb 重打包/前缀重写/兜底配置/apt 钩子）全部就位；
    # 看不到本行说明仍在运行旧版 APK——源码修复必须构建安装后才会生效。
    if [ -x "$PREFIX/bin/linbox-reprefix" ]; then
        # rev 动态读取（fix9.2）：与 var/lib/linbox/install-revision 实际
        # 值一致，避免版本文案与部署内容脱节（历史上写死 fix8.5/rev 10）。
        _linbox_rev="$(cat "$PREFIX/var/lib/linbox/install-revision" 2>/dev/null)"
        echo "linbox: pkg 修复链路已激活 (fix9.2, rev ${_linbox_rev:-13})"
    else
        echo "linbox: 警告: linbox-reprefix 缺失，pkg 安装将走目录改名降级路径" >&2
    fi
    return 0
}
_linbox_ensure_dpkg_fix
unset -f _linbox_ensure_dpkg_fix

LINBOX_CMD_FIFO="$PREFIX/var/linbox.cmd"

_linbox_send() {
    if [ -p "$LINBOX_CMD_FIFO" ]; then
        ( printf '%s\n' "$*" > "$LINBOX_CMD_FIFO" & ) 2>/dev/null
    else
        echo "linbox: 命令桥不可用（App 未运行或 FIFO 缺失）" >&2
        return 1
    fi
}

theme() {
    if [ $# -eq 0 ]; then
        echo "用法: theme win95|xp|win7|win10|win11"
        return 1
    fi
    _linbox_send "theme $*"
}

start() {
    if [ $# -eq 0 ]; then
        echo "用法: start <应用名>，运行 apps 查看列表"
        return 1
    fi
    _linbox_send "start $*"
}

apps() {
    _linbox_send "apps"
}

open() {
    if [ $# -eq 0 ]; then
        echo "用法: open <url>"
        return 1
    fi
    _linbox_send "open $*"
}

winver() {
    _linbox_send "winver"
    echo "LinBox ${LINBOX_VERSION:-2.22.1} (Termux ${TERMUX_VERSION:-0.118.0} 移植)"
}
