# build-wine-ttt.yml
name: Build TTTWine (True WOW64 for Termux with Vulkan and Full GStreamer)

on:
  workflow_dispatch:
    inputs:
      wine_version:
        description: 'Wine 版本号 (例如: 9.9, 9.21, 9.22)'
        required: true
        default: '9.21'
        type: string

permissions:
  contents: write  # 允许 GITHUB_TOKEN 创建 Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 设置版本变量
      run: |
        echo "WINE_VERSION=${{ github.event.inputs.wine_version }}" >> $GITHUB_ENV
        echo "STAGING_VERSION=v${{ github.event.inputs.wine_version }}"
        echo "构建 Wine 版本: ${{ github.event.inputs.wine_version }}"
        echo "Staging 补丁版本: v${{ github.event.inputs.wine_version }}"

    - name: 下载 bootstraps
      uses: dawidd6/action-download-artifact@v3
      with:
        workflow: bootstraps.yml
        workflow_conclusion: success
        path: /opt

    - name: 安装构建依赖
      run: |
        sudo apt update
        # 先修复损坏的依赖
        sudo apt --fix-broken install -y
        sudo apt install -y \
          debootstrap \
          perl \
          git \
          wget \
          xz-utils \
          bubblewrap \
          autoconf \
          flex \
          bison \
          gcc-multilib \
          g++-multilib \
          libx11-dev \
          libxext-dev \
          libxi-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libxfixes-dev \
          libxxf86vm-dev \
          libxrender-dev \
          libxinerama-dev \
          libgl-dev \
          libglu-dev \
          libosmesa6-dev \
          libfreetype6-dev \
          libfontconfig1-dev \
          libpcap-dev \
          libdbus-1-dev \
          libssl-dev \
          libasound2-dev \
          libpulse-dev \
          libudev-dev \
          libcups2-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff-dev \
          libxml2-dev \
          libvulkan-dev \
          vulkan-tools \
          libvulkan1 \
          mesa-vulkan-drivers \
          mingw-w64 \
          gettext \
          libgettextpo-dev \
          locales \
          language-pack-zh-hans

    - name: 安装多媒体和音频依赖
      run: |
        # 先安装 libunwind-dev 解决依赖问题
        sudo apt install -y libunwind-dev
        # 然后安装多媒体相关包
        sudo apt install -y \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libmpg123-dev \
          libopenal-dev

    - name: 设置中文语言环境
      run: |
        sudo locale-gen zh_CN.UTF-8
        sudo update-locale LANG=zh_CN.UTF-8
        export LANG=zh_CN.UTF-8
        export LC_ALL=zh_CN.UTF-8

    - name: 解压 bootstraps
      run: |
        sudo tar -C /opt -xpf /opt/Bootstraps/bootstraps.tar.xz
        echo "Bootstraps 解压完成"

    - name: 克隆 Wine 源码
      run: |
        git clone https://gitlab.winehq.org/wine/wine.git
        cd wine
        git checkout wine-${{ env.WINE_VERSION }}
        
    - name: 下载并应用 staging 补丁
      run: |
        cd wine
        # 下载 staging 补丁集
        wget -O wine-staging-${{ env.WINE_VERSION }}.tar.gz https://github.com/wine-staging/wine-staging/archive/refs/tags/v${{ env.WINE_VERSION }}.tar.gz
        tar -xzf wine-staging-${{ env.WINE_VERSION }}.tar.gz
    
        # 应用 staging 补丁 - 使用正确的路径
        cd wine-staging-${{ env.WINE_VERSION }}/staging
        chmod +x patchinstall.py
    
        # 应用所有补丁到 Wine 源码目录（上级的上级目录）
        ./patchinstall.py --all --destdir=../../
    
        echo "✅ Staging 补丁应用完成"

    - name: 验证 staging 补丁应用
      run: |
        cd wine
        echo "检查 staging 补丁应用情况..."
        if [ -f "dlls/ntdll/unix/esync.c" ]; then
            echo "✅ esync 支持已通过 staging 补丁添加"
        else
            echo "❌ esync 支持未找到"
        fi

    - name: 根据版本选择修复方式
      run: |
        cd wine
        
        # 解析版本号进行比较
        VERSION_MAJOR=$(echo ${{ env.WINE_VERSION }} | cut -d. -f1)
        VERSION_MINOR=$(echo ${{ env.WINE_VERSION }} | cut -d. -f2)
        
        echo "Wine 版本: ${{ env.WINE_VERSION }}"
        echo "主版本: $VERSION_MAJOR, 次版本: $VERSION_MINOR"
        
        # 判断版本是否 >= 9.10
        if [ $VERSION_MAJOR -gt 9 ] || [ $VERSION_MAJOR -eq 9 -a $VERSION_MINOR -ge 10 ]; then
            echo "使用 9.10+ 版本的修复方式 (wine_do_not_create_dxgi_manager2.patch)"
            echo "PATCH_TYPE=wine_do_not_create_dxgi_manager2" >> $GITHUB_ENV
        else
            echo "使用 9.10 以下版本的修复方式 (fix_wine9.2_mfplat.sh)"
            echo "PATCH_TYPE=fix_wine9_2_mfplat" >> $GITHUB_ENV
        fi

    - name: 应用 9.10 以下版本修复
      if: env.PATCH_TYPE == 'fix_wine9_2_mfplat'
      run: |
        cd wine
        echo "下载并应用 fix_wine9.2_mfplat.sh..."
        wget -O fix_wine9.2_mfplat.sh https://github.com/afeimod/linbox/raw/main/path/fix_wine9.2_mfplat.sh
        chmod +x fix_wine9.2_mfplat.sh
        ./fix_wine9.2_mfplat.sh
        echo "✅ 9.10 以下版本修复完成"

    - name: 应用 9.10 及以上版本修复
      if: env.PATCH_TYPE == 'wine_do_not_create_dxgi_manager2'
      run: |
        cd wine
        echo "下载并应用 wine_do_not_create_dxgi_manager2.patch..."
        wget https://github.com/afeimod/linbox/raw/main/path/wine_do_not_create_dxgi_manager2.patch
        
        # 检查目标文件是否存在
        if [ -f "dlls/mfplat/main.c" ]; then
            echo "找到目标文件 dlls/mfplat/main.c，准备应用补丁..."
            
            # 尝试应用补丁
            if patch -p1 < wine_do_not_create_dxgi_manager2.patch; then
                echo "✅ 补丁应用成功"
            else
                echo "❌ 补丁应用失败"
                exit 1
            fi
        else
            echo "❌ 错误：目标文件 dlls/mfplat/main.c 不存在"
            exit 1
        fi

    - name: 彻底修复 Termux 路径问题
      run: |
        cd wine
        
        echo "彻底修复 Termux 路径问题..."
        
        # 修改所有硬编码的 /tmp 路径
        find . -type f \( -name "*.c" -o -name "*.h" -o -name "*.in" -o -name "*.spec" \) -exec grep -l "/tmp" {} \; | xargs sed -i 's|/tmp/|/data/data/com.termux/files/usr/tmp/|g'
        
        # 修改 server 目录中的特定路径
        find server -type f \( -name "*.c" -o -name "*.h" \) -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} +
        
        # 修改其他关键文件
        find . -name "file.c" -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} +
        find . -name "loader.c" -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} +
        find . -name "server.c" -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} +
        
        echo "路径修复完成"

    - name: 使用 build_wine.sh 构建 WOW64 Wine
      run: |
        # 复制修改后的 Wine 源码到自定义路径
        cp -r wine $HOME/wine-custom-src
        
        # 下载 build_wine.sh 脚本
        wget -O build_wine.sh https://raw.githubusercontent.com/afeimod/linbox/refs/heads/main/path/build_wine.sh
        chmod +x build_wine.sh
        
        # 设置环境变量
        export WINE_VERSION="${{ env.WINE_VERSION }}"
        export WINE_BRANCH="staging"
        export EXPERIMENTAL_WOW64="true"
        export CUSTOM_SRC_PATH="$HOME/wine-custom-src"
        export USE_CCACHE="false"
        export BUILD_DIR="$HOME/build_wine"
        
        # 设置构建选项，启用 Vulkan 和 GStreamer
        export WINE_BUILD_OPTIONS="--enable-win64 --enable-archs=i386,x86_64 --with-x --with-vulkan --with-alsa --with-pulse --with-freetype --with-fontconfig --with-gstreamer --with-gettext --enable-nls --without-dbus --without-sane --without-pcap --without-pcsclite --disable-winemenubuilder --disable-win16 --disable-debug --disable-tests --without-piper --without-xinerama --without-cups --without-capi --without-coreaudio --without-gphoto --without-osmesa --without-oss --without-udev --without-unwind --without-usb --without-v4l2 --without-wayland"
        
        # 运行构建脚本
        ./build_wine.sh
        
        echo "✅ WOW64 Wine 构建完成"

    - name: 准备打包
      run: |
        # 查找构建产物
        BUILD_NAME="wine-${{ env.WINE_VERSION }}-staging-amd64-wow64"
        if [ -f "$HOME/$BUILD_NAME.tar.xz" ]; then
            echo "找到构建产物: $HOME/$BUILD_NAME.tar.xz"
            cp "$HOME/$BUILD_NAME.tar.xz" ./
        else
            # 尝试在脚本目录查找
            find $HOME -name "wine-*-amd64-wow64.tar.xz" -exec cp {} ./ \;
        fi
        
        # 重命名产物
        for file in wine-*-amd64-wow64.tar.xz; do
            if [ -f "$file" ]; then
                mv "$file" "wine-${{ env.WINE_VERSION }}-true-wow64-bin-gstreamer-termux.tar.xz"
                echo "重命名产物: $file -> wine-${{ env.WINE_VERSION }}-true-wow64-bin-gstreamer-termux.tar.xz"
            fi
        done
        
        # 如果找不到产物，创建错误
        if [ ! -f "wine-${{ env.WINE_VERSION }}-true-wow64-bin-gstreamer-termux.tar.xz" ]; then
            echo "❌ 错误：找不到构建产物"
            ls -la $HOME/*.tar.xz || true
            exit 1
        fi

    - name: 验证构建产物
      run: |
        echo "检查构建产物..."
        ls -lh wine-*.tar.xz
        
        # 检查文件内容
        tar -tf wine-${{ env.WINE_VERSION }}-true-wow64-bin-gstreamer-termux.tar.xz | head -20
        echo "..."
        tar -tf wine-${{ env.WINE_VERSION }}-true-wow64-bin-gstreamer-termux.tar.xz | grep -E "(vulkan|gst)" | head -10

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: wine-${{ env.WINE_VERSION }}-true-wow64-bin-gstreamer-termux
        path: wine-${{ env.WINE_VERSION }}-true-wow64-bin-gstreamer-termux.tar.xz

    - name: 发布到 GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.WINE_VERSION }}-true-wow64-gstreamer
        name: Wine ${{ env.WINE_VERSION }} (True WOW64 with Vulkan & GStreamer for Termux)
        body: |
          # Wine ${{ env.WINE_VERSION }} - True WOW64 with Vulkan & GStreamer for Termux
          
          ## 版本信息
          - **Wine 版本**: ${{ env.WINE_VERSION }}
          - **架构**: True WOW64 (同时支持 32 位和 64 位 Windows 应用程序)
          - **平台**: Termux (Android)
          - **图形 API**: Vulkan 支持已启用
          - **多媒体**: 完整 GStreamer 支持（包含 FFmpeg 插件）
          - **构建方式**: 基于 wine-exp-wow64 的改进构建
          
          ## 特性
          ✓ 真正的 WOW64 架构
          ✓ 同时支持 32 位和 64 位 Windows 应用程序
          ✓ Vulkan 图形 API 支持
          ✓ 完整的 GStreamer 支持
          ✓ 中文环境支持
          ✓ 应用了关键补丁提升兼容性
          ✓ 修复了 Termux 路径问题

          ## 构建信息
          - 构建时间: ${{ github.event.head_commit.timestamp }}
          - 提交: ${{ github.sha }}
          - 工作流: ${{ github.workflow }}
          - 修复方式: ${{ env.PATCH_TYPE }}
        files: wine-${{ env.WINE_VERSION }}-true-wow64-bin-gstreamer-termux.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 输出版本信息
      run: |
        echo "✅ True WOW64 Wine with Vulkan and Full GStreamer 构建完成"
        echo "版本号: ${{ env.WINE_VERSION }}"
        echo "架构: x86_64 True WOW64"
        echo "环境: Termux"
        echo "图形 API: Vulkan 支持已启用"
        echo "多媒体: 完整 GStreamer 支持"
        echo "修复方式: ${{ env.PATCH_TYPE }}"
        echo "构建方式: 基于 wine-exp-wow64 改进"
        echo ""
        echo "修复的问题:"
        echo "✓ 无法运行 EXE 文件"
        echo "✓ 中文环境支持"
        echo "✓ Vulkan 支持"
        echo "✓ 完整的 GStreamer 支持"
        echo "✓ 应用了关键补丁，提升兼容性"
        echo "✓ Termux 路径问题修复"
        echo "✓ 使用改进的 WOW64 构建方式"