# build-wine-lite.yml
name: Build TestWine (Lite WOW64 for Termux Full GStreamer)

on:
  workflow_dispatch:
    inputs:
      wine_version:
        description: 'Wine 版本号 (例如: 9.9, 9.21, 9.22)'
        required: true
        default: '9.21'
        type: string
      wine_type:
        description: 'Wine 版本类型'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - beta
          - wine-tkg

permissions:
  contents: write  # 允许 GITHUB_TOKEN 创建 Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: 设置版本变量
      run: |
        echo "WINE_VERSION=${{ github.event.inputs.wine_version }}" >> $GITHUB_ENV
        echo "WINE_TYPE=${{ github.event.inputs.wine_type }}" >> $GITHUB_ENV
        echo "STAGING_VERSION=v${{ github.event.inputs.wine_version }}"
        echo "构建 Wine 版本: ${{ github.event.inputs.wine_version }}"
        echo "Wine 类型: ${{ github.event.inputs.wine_type }}"
        if [ "${{ github.event.inputs.wine_type }}" = "staging" ]; then
          echo "Staging 补丁版本: v${{ github.event.inputs.wine_version }}"
        fi

    - name: 安装构建依赖
      run: |
        sudo apt update
        # 先修复损坏的依赖
        sudo apt --fix-broken install -y
        sudo apt install -y \
          debootstrap \
          perl \
          git \
          wget \
          xz-utils \
          bubblewrap \
          autoconf \
          flex \
          bison \
          gcc-multilib \
          g++-multilib \
          libx11-dev \
          libxext-dev \
          libxi-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libxfixes-dev \
          libxxf86vm-dev \
          libxrender-dev \
          libxinerama-dev \
          libgl-dev \
          libglu-dev \
          libosmesa6-dev \
          libfreetype6-dev \
          libfontconfig1-dev \
          libpcap-dev \
          libdbus-1-dev \
          libssl-dev \
          libasound2-dev \
          libpulse-dev \
          libudev-dev \
          libcups2-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff-dev \
          libxml2-dev \
          libvulkan-dev \
          vulkan-tools \
          libvulkan1 \
          mesa-vulkan-drivers \
          mingw-w64 \
          gettext \
          libgettextpo-dev \
          locales \
          language-pack-zh-hans

    - name: 安装多媒体和音频依赖
      run: |
        # 先安装 libunwind-dev 解决依赖问题
        sudo apt install -y libunwind-dev
        # 然后安装多媒体相关包
        sudo apt install -y \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libmpg123-dev \
          libopenal-dev

    - name: 设置中文语言环境
      run: |
        sudo locale-gen zh_CN.UTF-8
        sudo update-locale LANG=zh_CN.UTF-8
        export LANG=zh_CN.UTF-8
        export LC_ALL=zh_CN.UTF-8

    - name: 检查工作目录
      run: |
        echo "当前工作目录: $(pwd)"
        ls -la
        echo "构建版本: ${{ env.WINE_VERSION }}"
        echo "Wine 类型: ${{ env.WINE_TYPE }}"

    - name: 克隆 Wine 源码 (Staging/Beta)
      if: env.WINE_TYPE == 'staging' || env.WINE_TYPE == 'beta'
      run: |
        git clone https://github.com/wine-mirror/wine.git
        cd wine
        git checkout wine-${{ env.WINE_VERSION }}

    - name: 克隆 Wine-TKG 源码
      if: env.WINE_TYPE == 'wine-tkg'
      run: |
        git clone https://github.com/Kron4ek/wine-tkg.git
        cd wine-tkg
        # 检查对应的版本标签或分支
        if git checkout ${{ env.WINE_VERSION }} 2>/dev/null || git checkout wine-${{ env.WINE_VERSION }} 2>/dev/null; then
          echo "成功切换到版本 ${{ env.WINE_VERSION }}"
        else
          echo "使用默认分支"
          git checkout master
        fi

    - name: 下载并应用 staging 补丁 (仅 Staging 版本)
      if: env.WINE_TYPE == 'staging'
      run: |
        cd wine
        # 下载 staging 补丁集
        wget -O wine-staging-${{ env.WINE_VERSION }}.tar.gz https://github.com/wine-staging/wine-staging/archive/refs/tags/v${{ env.WINE_VERSION }}.tar.gz
        tar -xzf wine-staging-${{ env.WINE_VERSION }}.tar.gz
    
        # 应用 staging 补丁 - 使用正确的路径
        cd wine-staging-${{ env.WINE_VERSION }}/staging
        chmod +x patchinstall.py
    
        # 应用所有补丁到 Wine 源码目录（上级的上级目录）
        ./patchinstall.py --all --destdir=../../
    
        echo "✅ Staging 补丁应用完成"

    - name: 验证 staging 补丁应用 (仅 Staging 版本)
      if: env.WINE_TYPE == 'staging'
      run: |
        cd wine
        echo "检查 staging 补丁应用情况..."
        if [ -f "dlls/ntdll/unix/esync.c" ]; then
            echo "✅ esync 支持已通过 staging 补丁添加"
        else
            echo "❌ esync 支持未找到"
        fi

    - name: 根据版本选择修复方式
      run: |
        # 根据 Wine 类型选择正确的目录
        if [ "${{ env.WINE_TYPE }}" = "wine-tkg" ]; then
          cd wine-tkg
          SOURCE_DIR="wine-tkg"
        else
          cd wine
          SOURCE_DIR="wine"
        fi
        
        # 解析版本号进行比较
        VERSION_MAJOR=$(echo ${{ env.WINE_VERSION }} | cut -d. -f1)
        VERSION_MINOR=$(echo ${{ env.WINE_VERSION }} | cut -d. -f2)
        
        echo "Wine 版本: ${{ env.WINE_VERSION }}"
        echo "Wine 类型: ${{ env.WINE_TYPE }}"
        echo "源码目录: $SOURCE_DIR"
        echo "主版本: $VERSION_MAJOR, 次版本: $VERSION_MINOR"
        
        # 判断版本是否 >= 9.10
        if [ $VERSION_MAJOR -gt 9 ] || [ $VERSION_MAJOR -eq 9 -a $VERSION_MINOR -ge 10 ]; then
            echo "使用 9.10+ 版本的修复方式 (wine_do_not_create_dxgi_manager2.patch)"
            echo "PATCH_TYPE=wine_do_not_create_dxgi_manager2" >> $GITHUB_ENV
        else
            echo "使用 9.10 以下版本的修复方式 (fix_wine9.2_mfplat.sh)"
            echo "PATCH_TYPE=fix_wine9_2_mfplat" >> $GITHUB_ENV
        fi
        
        echo "SOURCE_DIR=$SOURCE_DIR" >> $GITHUB_ENV

    - name: 应用 9.10 以下版本修复
      if: env.PATCH_TYPE == 'fix_wine9_2_mfplat'
      run: |
        cd ${{ env.SOURCE_DIR }}
        echo "下载并应用 fix_wine9.2_mfplat.sh..."
        wget -O fix_wine9.2_mfplat.sh https://github.com/afeimod/linbox/raw/main/path/fix_wine9.2_mfplat.sh
        chmod +x fix_wine9.2_mfplat.sh
        ./fix_wine9.2_mfplat.sh
        echo "✅ 9.10 以下版本修复完成"

    - name: 应用 9.10 及以上版本修复
      if: env.PATCH_TYPE == 'wine_do_not_create_dxgi_manager2'
      run: |
        cd ${{ env.SOURCE_DIR }}
        echo "下载并应用 wine_do_not_create_dxgi_manager2.patch..."
        wget https://github.com/afeimod/linbox/raw/main/path/wine_do_not_create_dxgi_manager2.patch
        
        # 检查目标文件是否存在
        if [ -f "dlls/mfplat/main.c" ]; then
            echo "找到目标文件 dlls/mfplat/main.c，准备应用补丁..."
            
            # 尝试应用补丁
            if patch -p1 < wine_do_not_create_dxgi_manager2.patch; then
                echo "✅ 补丁应用成功"
            else
                echo "❌ 补丁应用失败"
                exit 1
            fi
        else
            echo "❌ 错误：目标文件 dlls/mfplat/main.c 不存在"
            exit 1
        fi

    - name: 彻底修复 Termux 路径问题
      run: |
        cd ${{ env.SOURCE_DIR }}
        
        echo "彻底修复 Termux 路径问题..."
        
        # 修改所有硬编码的 /tmp 路径
        find . -type f \( -name "*.c" -o -name "*.h" -o -name "*.in" -o -name "*.spec" \) -exec grep -l "/tmp" {} \; | xargs sed -i 's|/tmp/|/data/data/com.termux/files/usr/tmp/|g'
        
        # 修改 server 目录中的特定路径
        find server -type f \( -name "*.c" -o -name "*.h" \) -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} +
        
        # 修改其他关键文件
        find . -name "file.c" -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} +
        find . -name "loader.c" -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} +
        find . -name "server.c" -exec sed -i 's|"/tmp"|"/data/data/com.termux/files/usr/tmp"|g' {} +
        
        echo "路径修复完成"

    - name: 配置和构建真正的 WOW64 Wine（启用 Vulkan 和完整 GStreamer）
      run: |
        cd ${{ env.SOURCE_DIR }}
        mkdir -p /tmp/wine-install
        sudo chmod 777 -R /tmp/wine-install

        # 创建构建目录
        mkdir -p build-wow64
        cd build-wow64
        export CROSSCC="x86_64-w64-mingw32-gcc"
        export CROSSCXX="x86_64-w64-mingw32-g++"
        export CFLAGS="-march=x86-64 -msse3 -mfpmath=sse -O3 -ftree-vectorize -pipe"
        export CXXFLAGS="-march=x86-64 -msse3 -mfpmath=sse -O3 -ftree-vectorize -pipe"
        export CROSSCFLAGS="-march=x86-64 -msse3 -mfpmath=sse -O3 -ftree-vectorize -pipe"
        export CROSSCXXFLAGS="-march=x86-64 -msse3 -mfpmath=sse -O3 -ftree-vectorize -pipe"

        # 配置真正的 WOW64 Wine，启用 Vulkan 和完整 GStreamer 支持
        ../configure \
          --enable-win64 \
          --enable-archs=i386,x86_64 \
          --prefix=/tmp/wine-install \
          --with-x \
          --with-vulkan \
          --with-alsa \
          --with-pulse \
          --with-freetype \
          --with-fontconfig \
          --with-gstreamer \
          --with-gettext \
          --enable-nls \
          --without-dbus \
          --without-sane \
          --without-pcap \
          --without-pcsclite \
          --disable-winemenubuilder \
          --disable-win16 \
          --disable-debug \
          --disable-tests \
          --without-piper \
          --without-xinerama \
          --without-cups \
          --without-capi \
          --without-coreaudio \
          --without-gphoto \
          --without-osmesa \
          --without-oss \
          --without-udev \
          --without-unwind \
          --without-usb \
          --without-v4l2 \
          --without-wayland

        # 构建真正的 WOW64 Wine
        echo "开始构建支持 Vulkan 和完整 GStreamer 的 WOW64 Wine..."
        make -j$(nproc)

    - name: 安装 Wine 并获取版本信息
      run: |
        cd ${{ env.SOURCE_DIR }}/build-wow64
        # 安装 WOW64 Wine
        make install

        # 使用输入版本号
        VERSION="${{ env.WINE_VERSION }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Wine 版本: $VERSION - 类型: ${{ env.WINE_TYPE }} - 支持 Vulkan 和完整 GStreamer 的 WOW64 构建"

    - name: 验证 Vulkan 和 GStreamer 支持
      run: |
        echo "检查 Vulkan 支持..."
        if [ -f "/tmp/wine-install/bin/wine" ]; then
          echo "Wine 二进制文件存在"
        else
          echo "错误: Wine 二进制文件不存在"
          exit 1
        fi
        
        echo "检查 Vulkan 相关文件..."
        find /tmp/wine-install -name "*vulkan*" | head -10
        echo ""
        echo "检查 winevulkan.dll..."
        find /tmp/wine-install -name "winevulkan.dll*" | head -5
        echo ""
        echo "检查 GStreamer 支持..."
        find /tmp/wine-install -name "*gst*" | head -10

    - name: 准备打包
      run: |
        # 创建打包目录，使用新的目录结构
        PACKAGE_NAME="wine-${{ env.WINE_VERSION }}-${{ env.WINE_TYPE }}-linbox-wow64"
        mkdir -p wine-package/$PACKAGE_NAME
        
        # 复制 Wine 安装文件到新的目录
        echo "复制 Wine 文件到 $PACKAGE_NAME..."
        cp -r /tmp/wine-install/* wine-package/$PACKAGE_NAME/

    - name: 创建打包文件
      run: |
        PACKAGE_NAME="wine-${{ env.WINE_VERSION }}-${{ env.WINE_TYPE }}-linbox-wow64"
        
        echo "最终文件结构:"
        find wine-package -type f | sort
        echo ""
        echo "检查 Vulkan 相关文件:"
        find wine-package -name "*vulkan*" | sort
        echo ""
        echo "检查 GStreamer 相关文件:"
        find wine-package -name "*gst*" | sort
        
        # 使用 tar.xz 格式打包
        tar -cJf $PACKAGE_NAME.tar.xz -C wine-package $PACKAGE_NAME
        
        echo "打包完成:"
        ls -lh *.tar.xz

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: wine-${{ env.WINE_VERSION }}-${{ env.WINE_TYPE }}-linbox-wow64
        path: wine-${{ env.WINE_VERSION }}-${{ env.WINE_TYPE }}-linbox-wow64.tar.xz

    - name: 发布到 GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.WINE_VERSION }}-${{ env.WINE_TYPE }}-linbox-wow64
        name: Wine ${{ env.WINE_VERSION }} ${{ env.WINE_TYPE }} (Linbox WOW64 with Vulkan & GStreamer for Termux)
        body: |
          # Wine ${{ env.WINE_VERSION }} ${{ env.WINE_TYPE }} - Linbox WOW64 with Vulkan & GStreamer for Termux
          
          ## 版本信息
          - **Wine 版本**: ${{ env.WINE_VERSION }}
          - **Wine 类型**: ${{ env.WINE_TYPE }}
          - **架构**: True WOW64 (同时支持 32 位和 64 位 Windows 应用程序)
          - **平台**: Termux (Android)
          - **图形 API**: Vulkan 支持已启用
          - **多媒体**: 完整 GStreamer 支持（包含 FFmpeg 插件）
          
          ## 特性
          ✓ 真正的 WOW64 架构
          ✓ 同时支持 32 位和 64 位 Windows 应用程序
          ✓ Vulkan 图形 API 支持
          ✓ 完整的 GStreamer 支持
          ✓ 中文环境支持
          ✓ 应用了关键补丁提升兼容性

          ## 安装说明
          解压后，将 `wine-${{ env.WINE_VERSION }}-${{ env.WINE_TYPE }}-linbox-wow64` 文件夹放置在 Termux 的合适位置，并设置环境变量。

          ## 构建信息
          - 构建时间: ${{ github.event.head_commit.timestamp }}
          - 提交: ${{ github.sha }}
          - 工作流: ${{ github.workflow }}
        files: wine-${{ env.WINE_VERSION }}-${{ env.WINE_TYPE }}-linbox-wow64.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 输出版本信息
      run: |
        echo "✅ Linbox WOW64 Wine with Vulkan and Full GStreamer 构建完成"
        echo "版本号: ${{ env.WINE_VERSION }}"
        echo "Wine 类型: ${{ env.WINE_TYPE }}"
        echo "包名称: wine-${{ env.WINE_VERSION }}-${{ env.WINE_TYPE }}-linbox-wow64.tar.xz"
        echo "架构: x86_64 True WOW64"
        echo "环境: Termux"
        echo "图形 API: Vulkan 支持已启用"
        echo "多媒体: 完整 GStreamer 支持"
        echo "修复方式: ${{ env.PATCH_TYPE }}"
        echo ""
        echo "修复的问题:"
        echo "✓ 无法运行 EXE 文件"
        echo "✓ 中文环境支持"
        echo "✓ Vulkan 支持"
        echo "✓ 完整的 GStreamer 支持"
        echo "✓ 应用了关键补丁，提升兼容性"