# build-zink.yml
name: Build Mesa zink (aarch64)

on:
  workflow_dispatch:  # 只保留手动触发

permissions:
  contents: write  # 允许 GITHUB_TOKEN 创建 Release

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: 检出源码
      uses: actions/checkout@v4

    - name: 安装依赖
      run: |
        sudo sed -i "s/^Types: deb$/Types: deb deb-src/" /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt-get build-dep mesa -y

    - name: 克隆 Mesa
      run: |
        git clone https://gitlab.freedesktop.org/mesa/mesa.git
        cd mesa
        # 如果需要固定版本，可以取消下面注释
        # git checkout mesa-24.2.5

    - name: 构建 Mesa
      run: |
        cd mesa
        sudo mkdir -p /data/data/com.termux/files/usr/glibc
        sudo chmod 777 -R /data

        mkdir -p builddir
        meson setup builddir \
          --libdir=lib \
          --prefix=/data/data/com.termux/files/usr/glibc \
          -D opengl=true \
          -D gles1=enabled \
          -D gles2=enabled \
          -D platforms=x11 \
          -D glvnd=disabled \
          -D gallium-drivers=zink,llvmpipe \
          -D vulkan-drivers=[] \
          -D llvm=enabled \
          -D glx=xlib \
          -D glx-direct=true \
          -D xlib-lease=enabled

        ninja -C builddir
        ninja -C builddir install

        VERSION=$(cat VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        tar -czf termux-glibc-zink-${VERSION}-aarch64.tar.gz /data/data/com.termux/files/usr/glibc
        mv termux-glibc-zink-${VERSION}-aarch64.tar.gz ..

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: termux-glibc-zink-${{ env.VERSION }}-aarch64
        path: termux-glibc-zink-${{ env.VERSION }}-aarch64.tar.gz

    - name: 发布到 GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: zink ${{ env.VERSION }} (aarch64, Termux glibc)
        files: termux-glibc-zink-${{ env.VERSION }}-aarch64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 输出版本信息
      run: |
        echo "✅ Mesa 构建完成"
        echo "版本号: $VERSION"